// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char THING_ID[] = "5c5d8ce5-de32-46f7-b7fc-82257c701eba";   // Enter THING ID
const char DEVICE_LOGIN_NAME[] = "1833dfa9-485f-459c-a184-49abaecc9742";   // Enter DEVICE ID

const char SSID[] = SECRET_SSID;    // Network SSID (name)
const char PASS[] = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;    // Secret device password

void onRoomLightChange();
void onTvChange();
void onAirConditionChange();
void onOutDoorLightChange();
void onFanChange();  

CloudSwitch room_Light;
CloudSwitch tv;
CloudSwitch air_Condition;
CloudSwitch outDoor_Light;
CloudSwitch fan;   

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(room_Light, READWRITE, ON_CHANGE, onRoomLightChange);
  ArduinoCloud.addProperty(tv, READWRITE, ON_CHANGE, onTvChange);
  ArduinoCloud.addProperty(air_Condition, READWRITE, ON_CHANGE, onAirConditionChange);
  ArduinoCloud.addProperty(outDoor_Light, READWRITE, ON_CHANGE, onOutDoorLightChange);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);   
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);